---
name: docker-ansible-ubuntu Build

on:
  pull_request:
  push:
    branches:
      - "main"
  schedule:
    - cron: "00 0 * * 0"

jobs:
  centos7:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Test building images
        run: |
          scripts/build.sh 20.04
          scripts/build.sh 22.04

      - name: Run one of the built image.
        run: |
          docker run --name bmeme-docker-ansible-ubuntu2004 -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro bmeme/docker-ansible-ubuntu:20.04
          docker run --name bmeme-docker-ansible-ubuntu2204 -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro bmeme/docker-ansible-ubuntu:22.04

      - name: Verify Ansible is accessible
        run: docker exec --tty bmeme-docker-ansible-ubuntu2204 env TERM=xterm ansible --version